oppdrag:
  scope: api://prod-fss.okonomi.sokos-oppdrag-proxy/.default
  url: http://sokos-oppdrag-proxy.okonomi.svc.nais.local/
pen:
  url: http://pensjon-pen.pensjondeployer.svc.nais.local/api
  scope: api://prod-fss.pensjondeployer.pensjon-pen/.default
sam:
  url: https://sam.prod-fss-pub.nais.io
  scope: api://prod-fss.pensjonsamhandling.sam/.default
tp:
  url: https://tp-api.prod-fss-pub.nais.io
  scope: api://prod-fss.pensjonsamhandling.tp/.default
vedtak:
  samhandlersvar:
    topic: pensjonsamhandling.sam-vedtak-samhandlersvar-p
