oppdrag:
  url: http://sokos-oppdrag-proxy-q2.dev-fss-pub.nais.io
  scope: api://dev-fss.okonomi.sokos-oppdrag-proxy-q2/.default
pen:
  url: https://pensjon-pen-q2.dev-fss-pub.nais.io
  scope: api://dev-fss.pensjon-q2.pensjon-pen-q2/.default
sam:
  url: https://sam-q2.dev-fss-pub.nais.io
  scope: api://dev-fss.pensjonsamhandling.sam-q2/.default
tp:
  url: https://tp-q2.dev-fss-pub.nais.io
  scope: api://dev-fss.pensjonsamhandling.tp-q2/.default
vedtak:
  samhandlersvar:
    topic: pensjonsamhandling.sam-vedtak-samhandlersvar-q2
