apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjon-refusjonskrav
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://pensjon-refusjonskrav.intern.dev.nav.no
    - https://pensjon-refusjonskrav.dev-fss-pub.nais.io
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: sam-q2
          namespace: pensjonsamhandling
          cluster: dev-fss
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: refusjonskrav
          product: pensjon
          separator: /
          enabled: true
          delegationSource: altinn
          consumers:
            - name: SPK
              orgnr: 982583462
            - name: KLP
              orgnr: 938708606
            - name: GABLER PENSJONSTJENESTER AS
              orgnr: 916833520
            - name: OSLO PENSJONSFORSIKRING AS
              orgnr: 982759412
            - name: Storebrand Livsforsikring AS
              orgnr: 958995369
            - name: Storebrand Pensjonstjenester AS
              orgnr: 931936492
            - name: Viken
              orgnr: 974371359
            - name: Arendal kommunale pensjonskasse
              orgnr: 940380014
            - name: Drammen kommunale pensjonskasse
              orgnr: 980650383
            - name: Pensjonsordningen for apotekvirksomhet
              orgnr: 940291380
            - name: NAV
              orgnr: 889640782
            - name: Maritim pensjonskasse
              orgnr: 940415683
            - name: Garantikassen for fiskere
              orgnr: 974652382
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment.name=q2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm